"""
Action data models for ContextGuard.

All browser actions proposed by an AI agent must be represented as a
BrowserAction before they can be evaluated. This model is the single
entry-point for every action; the agent cannot reach Playwright directly.
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class ActionType(str, Enum):
    """Supported browser-automation action types."""
    navigate = "navigate"
    click = "click"
    fill = "fill"
    submit = "submit"
    upload = "upload"
    download = "download"
    extract = "extract"


class SourceType(str, Enum):
    """
    Where the instruction to perform an action came from.

    Untrusted sources (page_content, tool_output, unknown) are automatically
    tainted because they may carry attacker-controlled content.
    """
    system = "system"
    user = "user"
    trusted_content = "trusted_content"
    page_content = "page_content"
    tool_output = "tool_output"
    unknown = "unknown"


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------

class ActionTarget(BaseModel):
    """Describes the browser element or URL that an action targets."""
    url: Optional[str] = Field(None, description="Target URL for navigate/download actions")
    selector: Optional[str] = Field(None, description="CSS selector for element-level actions")
    element_type: Optional[str] = Field(None, description="HTML element type, e.g. input, form, button")
    field_name: Optional[str] = Field(None, description="Logical field name, e.g. password, card_number")

    @field_validator("url")
    @classmethod
    def validate_url(cls, v: Optional[str]) -> Optional[str]:
        """Reject obviously malformed URLs."""
        if v is None:
            return v
        v = v.strip()
        pattern = re.compile(
            r"^(https?://)?"
            r"([a-zA-Z0-9\-\.]+)"
            r"(\:[0-9]+)?"
            r"(/[^\s]*)?"
            r"(\?[^\s]*)?"
            r"(\#[^\s]*)?$"
        )
        if not pattern.match(v):
            raise ValueError(f"Malformed URL: {v!r}")
        return v


class ActionSource(BaseModel):
    """
    Describes where an action instruction originated.

    Untrusted page_content is tainted because a malicious web page can embed
    prompt-injection strings that try to hijack the agent's behaviour.
    """
    source_type: SourceType = Field(SourceType.unknown, description="Origin category")
    trusted: bool = Field(False, description="Whether this source is considered trusted")
    origin_url: Optional[str] = Field(None, description="URL the content came from")
    content: Optional[str] = Field(None, description="Raw content from the source (truncated for safety)")
    taint_id: Optional[str] = Field(None, description="Taint chain identifier propagated from a prior tainted event")

    @field_validator("content")
    @classmethod
    def limit_content_size(cls, v: Optional[str]) -> Optional[str]:
        """Prevent oversized content from being stored or processed."""
        if v is not None and len(v) > 4096:
            return v[:4096] + " [TRUNCATED]"
        return v


# ---------------------------------------------------------------------------
# Primary action model
# ---------------------------------------------------------------------------

class BrowserAction(BaseModel):
    """
    A structured browser action proposed by an AI agent.

    Every action must pass through ContextGuard's decision engine before the
    browser service is allowed to execute it. The agent has no direct path to
    Playwright; all automation runs through this model.
    """
    action_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique action identifier generated by ContextGuard"
    )
    session_id: str = Field(..., description="Session this action belongs to")
    agent_id: str = Field(..., description="Identifier of the proposing agent")
    action_type: ActionType = Field(..., description="Type of browser action")
    target: ActionTarget = Field(default_factory=ActionTarget, description="Action target")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Action payload data")
    source: ActionSource = Field(default_factory=ActionSource, description="Instruction source metadata")
    current_domain: Optional[str] = Field(None, description="Domain currently loaded in the browser")
    previous_domain: Optional[str] = Field(None, description="Domain visited before the current one")
    user_approved: bool = Field(False, description="Whether a human has pre-approved this action")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the action was proposed"
    )

    @field_validator("payload")
    @classmethod
    def reject_oversized_payload(cls, v: Dict[str, Any]) -> Dict[str, Any]:
        """Reject payloads that exceed a safe size limit."""
        import json
        serialised = json.dumps(v)
        if len(serialised) > 16_384:
            raise ValueError("Payload exceeds maximum allowed size of 16 KB")
        return v

    @model_validator(mode="after")
    def validate_action_requirements(self) -> "BrowserAction":
        """
        Enforce per-action-type validation rules:
        - navigate requires a URL
        - click/fill/submit/extract require a selector or element type
        - upload requires file metadata in the payload
        - download requires a URL or selector
        """
        action = self.action_type
        target = self.target

        if action == ActionType.navigate:
            if not target.url:
                raise ValueError("navigate action requires target.url")

        elif action in (ActionType.click, ActionType.fill, ActionType.submit):
            if not target.selector and not target.element_type:
                raise ValueError(f"{action.value} action requires target.selector or target.element_type")

        elif action == ActionType.upload:
            if not self.payload.get("file_path") and not self.payload.get("file_name"):
                raise ValueError("upload action requires payload.file_path or payload.file_name")

        elif action == ActionType.download:
            if not target.url and not target.selector:
                raise ValueError("download action requires target.url or target.selector")

        elif action == ActionType.extract:
            if not target.selector and not target.element_type:
                raise ValueError("extract action requires target.selector or target.element_type")

        return self

    class Config:
        use_enum_values = True


class ActionEvaluateRequest(BaseModel):
    """Request body for the /api/actions/evaluate endpoint."""
    action: BrowserAction


class ActionExecuteRequest(BaseModel):
    """Request body for the /api/actions/execute endpoint."""
    action: BrowserAction
